

**LOGICA DE FUZZY COM PYTHON: ESTUDO DE CASO GORJETA **

# **Antecedentes ( ENTRADAS )**

Servio: que nota você daria para o serviço, em uma escala de 0 a 10

    * Ruim, Aceitável, ótimo

Qualidade da comida: quão boa estava a comida, em uma escala de 0 a 10

    * Ruim, boa, Saborosa

# **Consequentes ( SAÍDAS )**

Gorjetas: quanta gorjeta você daria, entre 0% e 20%

    * Baixa, média, alta

# **REGRAS!!**

  * Se a qualidade da comida for ruim ou o serviço for ruim então, a gorjeta será baixa.
  * Se o serviço for médio então, a gorjeta será média

  * Se o serviço for bom e a qualidade da comida for saborosa, então a gorjeta sera alta



# **IMPORTAÇÃO DA BIBLIOTECAS **

In [3]:
!pip install scikit-fuzzy

In [4]:
import numpy as np
import skfuzzy as fuzzy
import matplotlib.pyplot as plt

**ANTECENDENTES E CONSEQUENTES**




In [5]:
np.arange(0, 11, 1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#criando as variaveis com array de 10 possições!
#intervalos possiveis para os resultados!!
x_comida = np.arange(0, 11, 1)
x_servico = np.arange(0, 11, 1)
x_gorjeta = np.arange(0, 21, 1)

In [8]:
x_comida, x_servico, x_gorjeta

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]))

QUALIDADE DA COMIDA!!

In [10]:
y_comida_ruim = fuzzy.trimf(x_comida, [0, 0, 5])

In [13]:
#QUANDO DEFINIMOS UMA PARAMETRO [0, 0, 5], O VALOR DE DECAIMENTO SERA DEPOIS DE 5 POSSIÇÕES, SENDO QUE NOSSO ARRAY SERIA DE 10
#TEREMOS O SEGUINTE RESULTADO:
y_comida_ruim

array([1. , 0.8, 0.6, 0.4, 0.2, 0. , 0. , 0. , 0. , 0. , 0. ])